name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and run tests
      run: xcodebuild test -scheme CoffeeToast -destination 'platform=iOS Simulator,name=iPhone 13 Pro'
